export const states = [
  { id: "abia", name: "Abia" },
  { id: "adamawa", name: "Adamawa" },
  { id: "anambra", name: "Anambra" },
  { id: "bayelsa", name: "Bayelsa" },
  { id: "borno", name: "Borno" },
  { id: "cross river", name: "Cross River" },
  { id: "delta", name: "Delta" },
  { id: "ebonyi", name: "Ebonyi" },
  { id: "edo", name: "Edo" },
  { id: "ekiti", name: "Ekiti" },
  { id: "enugu", name: "Enugu" },
  { id: "gombe", name: "Gombe" },
  { id: "imo", name: "Imo" },
  { id: "jigawa", name: "Jigawa" },
  { id: "kaduna", name: "Kaduna" },
  { id: "kano", name: "Kano" },
  { id: "katsina", name: "Katsina" },
  { id: "kebbi", name: "Kebbi" },
  { id: "kogi", name: "Kogi" },
  { id: "kwara", name: "Kwara" },
  { id: "lagos", name: "Lagos" },
  { id: "nasarawa", name: "Nasarawa" },
  { id: "niger", name: "Niger" },
  { id: "ogun", name: "Ogun" },
  { id: "ondo", name: "Ondo" },
  { id: "osun", name: "Osun" },
  { id: "oyo", name: "Oyo" },
  { id: "plateau", name: "Plateau" },
  { id: "rivers", name: "Rivers" },
  { id: "sokoto", name: "Sokoto" },
  { id: "taraba", name: "Taraba" },
  { id: "yobe", name: "Yobe" },
  { id: "zamfara", name: "Zamfara" },
  { id: "akwa ibom", name: "Akwa Ibom" },
  { id: "benue", name: "Benue" },
  { id: "bauchi", name: "Bauchi" },
];

export const LGA = [
{"id": "abadam", "name": "Abadam" },
{"id": "abaji", "name": "Abaji" },
{"id": "abak", "name": "Abak" },
{"id": "abakaliki", "name": "Abakaliki" },
{"id": "aba north", "name": "Aba North" },
{"id": "aba south", "name": "Aba South" },
{"id": "abeokuta north", "name": "Abeokuta North" },
{"id": "abeokuta south", "name": "Abeokuta South" },
{"id": "abi", "name": "Abi" },
{"id": "aboh mbaise", "name": "Aboh Mbaise" },
{"id": "abua/odual", "name": "Abua/Odual" },
{"id": "adavi", "name": "Adavi" },
{"id": "ado ekiti", "name": "Ado Ekiti" },
{"id": "ado-odo/ota", "name": "Ado-Odo/Ota" },
{"id": "afijio", "name": "Afijio" },
{"id": "afikpo north", "name": "Afikpo North" },
{"id": "afikpo south (edda)", "name": "Afikpo South (Edda)" },
{"id": "agaie", "name": "Agaie" },
{"id": "agatu", "name": "Agatu" },
{"id": "agwara", "name": "Agwara" },
{"id": "agege", "name": "Agege" },
{"id": "aguata", "name": "Aguata" },
{"id": "ahiazu mbaise", "name": "Ahiazu Mbaise" },
{"id": "ahoada east", "name": "Ahoada East" },
{"id": "ahoada west", "name": "Ahoada West" },
{"id": "ajaokuta", "name": "Ajaokuta" },
{"id": "ajeromi-ifelodun", "name": "Ajeromi-Ifelodun" },
{"id": "ajingi", "name": "Ajingi" },
{"id": "akamkpa", "name": "Akamkpa" },
{"id": "akinyele", "name": "Akinyele" },
{"id": "akko", "name": "Akko" },
{"id": "akoko-edo", "name": "Akoko-Edo" },
{"id": "akoko north-east", "name": "Akoko North-East" },
{"id": "akoko north-west", "name": "Akoko North-West" },
{"id": "akoko south-west", "name": "Akoko South-West" },
{"id": "akoko south-east", "name": "Akoko South-East" },
{"id": "akpabuyo", "name": "Akpabuyo" },
{"id": "akuku-toru", "name": "Akuku-Toru" },
{"id": "akure south", "name": "Akure South" },
{"id": "akure north", "name": "Akure North" },
{"id": "albasu", "name": "Albasu" },
{"id": "akwanga", "name": "Akwanga" },
{"id": "alimosho", "name": "Alimosho" },
{"id": "alkaleri", "name": "Alkaleri" },
{"id": "amuwo-odofin", "name": "Amuwo-Odofin" },
{"id": "anambra east", "name": "Anambra East" },
{"id": "anaocha", "name": "Anaocha" },
{"id": "anambra west", "name": "Anambra West" },
{"id": "andoni", "name": "Andoni" },
{"id": "aninri", "name": "Aninri" },
{"id": "aniocha south", "name": "Aniocha South" },
{"id": "aniocha north", "name": "Aniocha North" },
{"id": "anka", "name": "Anka" },
{"id": "ankpa", "name": "Ankpa" },
{"id": "apa", "name": "Apa" },
{"id": "apapa", "name": "Apapa" },
{"id": "ardo kola", "name": "Ardo Kola" },
{"id": "ado", "name": "Ado" },
{"id": "arewa dandi", "name": "Arewa Dandi" },
{"id": "argungu", "name": "Argungu" },
{"id": "arochukwu", "name": "Arochukwu" },
{"id": "asa", "name": "Asa" },
{"id": "asari-toru", "name": "Asari-Toru" },
{"id": "askira/uba", "name": "Askira/Uba" },
{"id": "atakunmosa west", "name": "Atakunmosa West" },
{"id": "atakunmosa east", "name": "Atakunmosa East" },
{"id": "atisbo", "name": "Atisbo" },
{"id": "atiba", "name": "Atiba" },
{"id": "augie", "name": "Augie" },
{"id": "auyo", "name": "Auyo" },
{"id": "awe", "name": "Awe" },
{"id": "awgu", "name": "Awgu" },
{"id": "awka north", "name": "Awka North" },
{"id": "awka south", "name": "Awka South" },
{"id": "aiyedaade", "name": "Aiyedaade" },
{"id": "ayamelum", "name": "Ayamelum" },
{"id": "babura", "name": "Babura" },
{"id": "aiyedire", "name": "Aiyedire" },
{"id": "badagry", "name": "Badagry" },
{"id": "bagudo", "name": "Bagudo" },
{"id": "bagwai", "name": "Bagwai" },
{"id": "bakassi", "name": "Bakassi" },
{"id": "bokkos", "name": "Bokkos" },
{"id": "bakori", "name": "Bakori" },
{"id": "bakura", "name": "Bakura" },
{"id": "balanga", "name": "Balanga" },
{"id": "bali", "name": "Bali" },
{"id": "bama", "name": "Bama" },
{"id": "bade", "name": "Bade" },
{"id": "barkin ladi", "name": "Barkin Ladi" },
{"id": "baruten", "name": "Baruten" },
{"id": "bassa", "name": "Bassa" },
{"id": "batagarawa", "name": "Batagarawa" },
{"id": "bassa", "name": "Bassa" },
{"id": "bauchi", "name": "Bauchi" },
{"id": "batsari", "name": "Batsari" },
{"id": "baure", "name": "Baure" },
{"id": "bayo", "name": "Bayo" },
{"id": "bebeji", "name": "Bebeji" },
{"id": "bekwarra", "name": "Bekwarra" },
{"id": "bende", "name": "Bende" },
{"id": "biase", "name": "Biase" },
{"id": "aleiro", "name": "Aleiro" },
{"id": "bichi", "name": "Bichi" },
{"id": "billiri", "name": "Billiri" },
{"id": "bida", "name": "Bida" },
{"id": "bindawa", "name": "Bindawa" },
{"id": "binji", "name": "Binji" },
{"id": "biriniwa", "name": "Biriniwa" },
{"id": "birnin gwari", "name": "Birnin Gwari" },
{"id": "birnin kebbi", "name": "Birnin Kebbi" },
{"id": "birnin kudu", "name": "Birnin Kudu" },
{"id": "birnin magaji/kiyaw", "name": "Birnin Magaji/Kiyaw" },
{"id": "biu", "name": "Biu" },
{"id": "bodinga", "name": "Bodinga" },
{"id": "bogoro", "name": "Bogoro" },
{"id": "boki", "name": "Boki" },
{"id": "boluwaduro", "name": "Boluwaduro" },
{"id": "bomadi", "name": "Bomadi" },
{"id": "bonny", "name": "Bonny" },
{"id": "borgu", "name": "Borgu" },
{"id": "boripe", "name": "Boripe" },
{"id": "bursari", "name": "Bursari" },
{"id": "bosso", "name": "Bosso" },
{"id": "brass", "name": "Brass" },
{"id": "buji", "name": "Buji" },
{"id": "bukkuyum", "name": "Bukkuyum" },
{"id": "buruku", "name": "Buruku" },
{"id": "bungudu", "name": "Bungudu" },
{"id": "bunkure", "name": "Bunkure" },
{"id": "bunza", "name": "Bunza" },
{"id": "burutu", "name": "Burutu" },
{"id": "bwari", "name": "Bwari" },
{"id": "calabar municipal", "name": "Calabar Municipal" },
{"id": "calabar south", "name": "Calabar South" },
{"id": "chanchaga", "name": "Chanchaga" },
{"id": "charanchi", "name": "Charanchi" },
{"id": "chibok", "name": "Chibok" },
{"id": "chikun", "name": "Chikun" },
{"id": "dala", "name": "Dala" },
{"id": "damaturu", "name": "Damaturu" },
{"id": "damban", "name": "Damban" },
{"id": "dambatta", "name": "Dambatta" },
{"id": "damboa", "name": "Damboa" },
{"id": "dandi", "name": "Dandi" },
{"id": "dandume", "name": "Dandume" },
{"id": "dange shuni", "name": "Dange Shuni" },
{"id": "danja", "name": "Danja" },
{"id": "dan musa", "name": "Dan Musa" },
{"id": "darazo", "name": "Darazo" },
{"id": "dass", "name": "Dass" },
{"id": "daura", "name": "Daura" },
{"id": "dawakin kudu", "name": "Dawakin Kudu" },
{"id": "dawakin tofa", "name": "Dawakin Tofa" },
{"id": "degema", "name": "Degema" },
{"id": "dekina", "name": "Dekina" },
{"id": "demsa", "name": "Demsa" },
{"id": "doguwa", "name": "Doguwa" },
{"id": "dikwa", "name": "Dikwa" },
{"id": "doma", "name": "Doma" },
{"id": "dunukofia", "name": "Dunukofia" },
{"id": "donga", "name": "Donga" },
{"id": "dukku", "name": "Dukku" },
{"id": "dutse", "name": "Dutse" },
{"id": "eastern obolo", "name": "Eastern Obolo" },
{"id": "dutsi", "name": "Dutsi" },
{"id": "dutsin ma", "name": "Dutsin Ma" },
{"id": "ebonyi", "name": "Ebonyi" },
{"id": "ede north", "name": "Ede North" },
{"id": "edati", "name": "Edati" },
{"id": "ede south", "name": "Ede South" },
{"id": "ife central", "name": "Ife Central" },
{"id": "edu", "name": "Edu" },
{"id": "ife east", "name": "Ife East" },
{"id": "ife north", "name": "Ife North" },
{"id": "ife south", "name": "Ife South" },
{"id": "efon", "name": "Efon" },
{"id": "yewa north", "name": "Yewa North" },
{"id": "yewa south", "name": "Yewa South" },
{"id": "egbeda", "name": "Egbeda" },
{"id": "ehime mbano", "name": "Ehime Mbano" },
{"id": "egor", "name": "Egor" },
{"id": "ejigbo", "name": "Ejigbo" },
{"id": "eket", "name": "Eket" },
{"id": "ekeremor", "name": "Ekeremor" },
{"id": "ekiti", "name": "Ekiti" },
{"id": "ekiti east", "name": "Ekiti East" },
{"id": "ekiti west", "name": "Ekiti West" },
{"id": "ekiti south-west", "name": "Ekiti South-West" },
{"id": "eleme", "name": "Eleme" },
{"id": "ekwusigo", "name": "Ekwusigo" },
{"id": "emuoha", "name": "Emuoha" },
{"id": "emure", "name": "Emure" },
{"id": "enugu east", "name": "Enugu East" },
{"id": "enugu south", "name": "Enugu South" },
{"id": "enugu north", "name": "Enugu North" },
{"id": "esan central", "name": "Esan Central" },
{"id": "epe", "name": "Epe" },
{"id": "esan south-east", "name": "Esan South-East" },
{"id": "esan north-east", "name": "Esan North-East" },
{"id": "ese odo", "name": "Ese Odo" },
{"id": "esan west", "name": "Esan West" },
{"id": "esit eket", "name": "Esit Eket" },
{"id": "essien udim", "name": "Essien Udim" },
{"id": "etche", "name": "Etche" },
{"id": "ethiope west", "name": "Ethiope West" },
{"id": "ethiope east", "name": "Ethiope East" },
{"id": "etinan", "name": "Etinan" },
{"id": "etim ekpo", "name": "Etim Ekpo" },
{"id": "etsako central", "name": "Etsako Central" },
{"id": "eti osa", "name": "Eti Osa" },
{"id": "etsako west", "name": "Etsako West" },
{"id": "etsako east", "name": "Etsako East" },
{"id": "etung", "name": "Etung" },
{"id": "ewekoro", "name": "Ewekoro" },
{"id": "ezeagu", "name": "Ezeagu" },
{"id": "ezza north", "name": "Ezza North" },
{"id": "ezinihitte", "name": "Ezinihitte" },
{"id": "fagge", "name": "Fagge" },
{"id": "ezza south", "name": "Ezza South" },
{"id": "fakai", "name": "Fakai" },
{"id": "faskari", "name": "Faskari" },
{"id": "funakaye", "name": "Funakaye" },
{"id": "fika", "name": "Fika" },
{"id": "fufure", "name": "Fufure" },
{"id": "fune", "name": "Fune" },
{"id": "funtua", "name": "Funtua" },
{"id": "gabasawa", "name": "Gabasawa" },
{"id": "gada", "name": "Gada" },
{"id": "ganjuwa", "name": "Ganjuwa" },
{"id": "gagarawa", "name": "Gagarawa" },
{"id": "gamawa", "name": "Gamawa" },
{"id": "ganye", "name": "Ganye" },
{"id": "garun mallam", "name": "Garun Mallam" },
{"id": "garki", "name": "Garki" },
{"id": "garko", "name": "Garko" },
{"id": "gashaka", "name": "Gashaka" },
{"id": "gassol", "name": "Gassol" },
{"id": "gaya", "name": "Gaya" },
{"id": "gayuk", "name": "Gayuk" },
{"id": "gbako", "name": "Gbako" },
{"id": "gezawa", "name": "Gezawa" },
{"id": "gboko", "name": "Gboko" },
{"id": "gbonyin", "name": "Gbonyin" },
{"id": "giwa", "name": "Giwa" },
{"id": "geidam", "name": "Geidam" },
{"id": "giade", "name": "Giade" },
{"id": "gokana", "name": "Gokana" },
{"id": "goronyo", "name": "Goronyo" },
{"id": "gombe", "name": "Gombe" },
{"id": "gombi", "name": "Gombi" },
{"id": "grie", "name": "Grie" },
{"id": "gudu", "name": "Gudu" },
{"id": "gubio", "name": "Gubio" },
{"id": "gujba", "name": "Gujba" },
{"id": "gulani", "name": "Gulani" },
{"id": "guma", "name": "Guma" },
{"id": "gumel", "name": "Gumel" },
{"id": "gummi", "name": "Gummi" },
{"id": "gurara", "name": "Gurara" },
{"id": "guri", "name": "Guri" },
{"id": "gusau", "name": "Gusau" },
{"id": "guzamala", "name": "Guzamala" },
{"id": "gwadabawa", "name": "Gwadabawa" },
{"id": "gwagwalada", "name": "Gwagwalada" },
{"id": "gwale", "name": "Gwale" },
{"id": "gwandu", "name": "Gwandu" },
{"id": "gwaram", "name": "Gwaram" },
{"id": "gwarzo", "name": "Gwarzo" },
{"id": "gwer east", "name": "Gwer East" },
{"id": "gwer west", "name": "Gwer West" },
{"id": "gwiwa", "name": "Gwiwa" },
{"id": "gwoza", "name": "Gwoza" },
{"id": "hadejia", "name": "Hadejia" },
{"id": "hawul", "name": "Hawul" },
{"id": "hong", "name": "Hong" },
{"id": "ibadan north", "name": "Ibadan North" },
{"id": "ibadan north-east", "name": "Ibadan North-East" },
{"id": "ibadan north-west", "name": "Ibadan North-West" },
{"id": "ibadan south-east", "name": "Ibadan South-East" },
{"id": "ibadan south-west", "name": "Ibadan South-West" },
{"id": "ibaji", "name": "Ibaji" },
{"id": "ibarapa central", "name": "Ibarapa Central" },
{"id": "ibarapa east", "name": "Ibarapa East" },
{"id": "ibarapa north", "name": "Ibarapa North" },
{"id": "ibeju-lekki", "name": "Ibeju-Lekki" },
{"id": "ibeno", "name": "Ibeno" },
{"id": "ibesikpo asutan", "name": "Ibesikpo Asutan" },
{"id": "ibi", "name": "Ibi" },
{"id": "ibiono-ibom", "name": "Ibiono-Ibom" },
{"id": "idah", "name": "Idah" },
{"id": "idanre", "name": "Idanre" },
{"id": "ideato north", "name": "Ideato North" },
{"id": "ideato south", "name": "Ideato South" },
{"id": "idemili north", "name": "Idemili North" },
{"id": "idemili south", "name": "Idemili South" },
{"id": "egbedore", "name": "Egbedore" },
{"id": "ido", "name": "Ido" },
{"id": "ido osi", "name": "Ido Osi" },
{"id": "ifako-ijaiye", "name": "Ifako-Ijaiye" },
{"id": "ifedayo", "name": "Ifedayo" },
{"id": "ifedore", "name": "Ifedore" },
{"id": "ifelodun", "name": "Ifelodun" },
{"id": "ifelodun", "name": "Ifelodun" },
{"id": "ifo", "name": "Ifo" },
{"id": "igabi", "name": "Igabi" },
{"id": "igalamela odolu", "name": "Igalamela Odolu" },
{"id": "igbo etiti", "name": "Igbo Etiti" },
{"id": "igbo eze north", "name": "Igbo Eze North" },
{"id": "igbo eze south", "name": "Igbo Eze South" },
{"id": "igueben", "name": "Igueben" },
{"id": "ihiala", "name": "Ihiala" },
{"id": "ihitte/uboma", "name": "Ihitte/Uboma" },
{"id": "ilaje", "name": "Ilaje" },
{"id": "ijebu east", "name": "Ijebu East" },
{"id": "ijebu north", "name": "Ijebu North" },
{"id": "ijebu north east", "name": "Ijebu North East" },
{"id": "ijebu ode", "name": "Ijebu Ode" },
{"id": "ijero", "name": "Ijero" },
{"id": "ijumu", "name": "Ijumu" },
{"id": "ika", "name": "Ika" },
{"id": "ika north east", "name": "Ika North East" },
{"id": "ikara", "name": "Ikara" },
{"id": "ika south", "name": "Ika South" },
{"id": "ikeduru", "name": "Ikeduru" },
{"id": "ikeja", "name": "Ikeja" },
{"id": "ikenne", "name": "Ikenne" },
{"id": "ikere", "name": "Ikere" },
{"id": "ikole", "name": "Ikole" },
{"id": "ikom", "name": "Ikom" },
{"id": "ikono", "name": "Ikono" },
{"id": "ikorodu", "name": "Ikorodu" },
{"id": "ikot abasi", "name": "Ikot Abasi" },
{"id": "ikot ekpene", "name": "Ikot Ekpene" },
{"id": "ikpoba okha", "name": "Ikpoba Okha" },
{"id": "ikwerre", "name": "Ikwerre" },
{"id": "ikwo", "name": "Ikwo" },
{"id": "ikwuano", "name": "Ikwuano" },
{"id": "ilejemeje", "name": "Ilejemeje" },
{"id": "ile oluji/okeigbo", "name": "Ile Oluji/Okeigbo" },
{"id": "ilesa east", "name": "Ilesa East" },
{"id": "ilesa west", "name": "Ilesa West" },
{"id": "illela", "name": "Illela" },
{"id": "ilorin east", "name": "Ilorin East" },
{"id": "ilorin south", "name": "Ilorin South" },
{"id": "ilorin west", "name": "Ilorin West" },
{"id": "imeko afon", "name": "Imeko Afon" },
{"id": "ingawa", "name": "Ingawa" },
{"id": "ini", "name": "Ini" },
{"id": "ila", "name": "Ila" },
{"id": "ipokia", "name": "Ipokia" },
{"id": "irele", "name": "Irele" },
{"id": "irepodun", "name": "Irepodun" },
{"id": "irepo", "name": "Irepo" },
{"id": "irepodun", "name": "Irepodun" },
{"id": "irepodun/ifelodun", "name": "Irepodun/Ifelodun" },
{"id": "irewole", "name": "Irewole" },
{"id": "isa", "name": "Isa" },
{"id": "ise/orun", "name": "Ise/Orun" },
{"id": "iseyin", "name": "Iseyin" },
{"id": "ishielu", "name": "Ishielu" },
{"id": "isiala mbano", "name": "Isiala Mbano" },
{"id": "isiala ngwa north", "name": "Isiala Ngwa North" },
{"id": "isiala ngwa south", "name": "Isiala Ngwa South" },
{"id": "isin", "name": "Isin" },
{"id": "isi uzo", "name": "Isi Uzo" },
{"id": "isokan", "name": "Isokan" },
{"id": "isoko north", "name": "Isoko North" },
{"id": "isu", "name": "Isu" },
{"id": "isoko south", "name": "Isoko South" },
{"id": "isuikwuato", "name": "Isuikwuato" },
{"id": "itas/gadau", "name": "Itas/Gadau" },
{"id": "itesiwaju", "name": "Itesiwaju" },
{"id": "itu", "name": "Itu" },
{"id": "iwajowa", "name": "Iwajowa" },
{"id": "ivo", "name": "Ivo" },
{"id": "izzi", "name": "Izzi" },
{"id": "jaba", "name": "Jaba" },
{"id": "jada", "name": "Jada" },
{"id": "jahun", "name": "Jahun" },
{"id": "jakusko", "name": "Jakusko" },
{"id": "jalingo", "name": "Jalingo" },
{"id": "iwo", "name": "Iwo" },
{"id": "jama'are", "name": "Jama'are" },
{"id": "jega", "name": "Jega" },
{"id": "jere", "name": "Jere" },
{"id": "jema'a", "name": "Jema'a" },
{"id": "jos east", "name": "Jos East" },
{"id": "jibia", "name": "Jibia" },
{"id": "jos north", "name": "Jos North" },
{"id": "jos south", "name": "Jos South" },
{"id": "kabo", "name": "Kabo" },
{"id": "kabba/bunu", "name": "Kabba/Bunu" },
{"id": "kachia", "name": "Kachia" },
{"id": "kaduna north", "name": "Kaduna North" },
{"id": "kaduna south", "name": "Kaduna South" },
{"id": "kafin hausa", "name": "Kafin Hausa" },
{"id": "kaga", "name": "Kaga" },
{"id": "kafur", "name": "Kafur" },
{"id": "kaiama", "name": "Kaiama" },
{"id": "kagarko", "name": "Kagarko" },
{"id": "kajola", "name": "Kajola" },
{"id": "kaita", "name": "Kaita" },
{"id": "kajuru", "name": "Kajuru" },
{"id": "kala/balge", "name": "Kala/Balge" },
{"id": "kalgo", "name": "Kalgo" },
{"id": "kaltungo", "name": "Kaltungo" },
{"id": "kanam", "name": "Kanam" },
{"id": "kankara", "name": "Kankara" },
{"id": "kanke", "name": "Kanke" },
{"id": "kano municipal", "name": "Kano Municipal" },
{"id": "karasuwa", "name": "Karasuwa" },
{"id": "karaye", "name": "Karaye" },
{"id": "karim lamido", "name": "Karim Lamido" },
{"id": "karu", "name": "Karu" },
{"id": "katagum", "name": "Katagum" },
{"id": "katcha", "name": "Katcha" },
{"id": "katsina", "name": "Katsina" },
{"id": "katsina-ala", "name": "Katsina-Ala" },
{"id": "kaura", "name": "Kaura" },
{"id": "kaura namoda", "name": "Kaura Namoda" },
{"id": "kauru", "name": "Kauru" },
{"id": "keana", "name": "Keana" },
{"id": "kebbe", "name": "Kebbe" },
{"id": "keffi", "name": "Keffi" },
{"id": "khana", "name": "Khana" },
{"id": "kibiya", "name": "Kibiya" },
{"id": "kirfi", "name": "Kirfi" },
{"id": "kiri kasama", "name": "Kiri Kasama" },
{"id": "kiru", "name": "Kiru" },
{"id": "kiyawa", "name": "Kiyawa" },
{"id": "kogi", "name": "Kogi" },
{"id": "koko/besse", "name": "Koko/Besse" },
{"id": "kokona", "name": "Kokona" },
{"id": "kolokuma/opokuma", "name": "Kolokuma/Opokuma" },
{"id": "konduga", "name": "Konduga" },
{"id": "konshisha", "name": "Konshisha" },
{"id": "kontagora", "name": "Kontagora" },
{"id": "kosofe", "name": "Kosofe" },
{"id": "kaugama", "name": "Kaugama" },
{"id": "kudan", "name": "Kudan" },
{"id": "kubau", "name": "Kubau" },
{"id": "kuje", "name": "Kuje" },
{"id": "kukawa", "name": "Kukawa" },
{"id": "kumbotso", "name": "Kumbotso" },
{"id": "kumi", "name": "Kumi" },
{"id": "kunchi", "name": "Kunchi" },
{"id": "kura", "name": "Kura" },
{"id": "kurfi", "name": "Kurfi" },
{"id": "kusada", "name": "Kusada" },
{"id": "kwali", "name": "Kwali" },
{"id": "kwande", "name": "Kwande" },
{"id": "kwami", "name": "Kwami" },
{"id": "kware", "name": "Kware" },
{"id": "kwaya kusar", "name": "Kwaya Kusar" },
{"id": "lafia", "name": "Lafia" },
{"id": "lagelu", "name": "Lagelu" },
{"id": "lagos island", "name": "Lagos Island" },
{"id": "lagos mainland", "name": "Lagos Mainland" },
{"id": "langtang south", "name": "Langtang South" },
{"id": "langtang north", "name": "Langtang North" },
{"id": "lapai", "name": "Lapai" },
{"id": "lamurde", "name": "Lamurde" },
{"id": "lau", "name": "Lau" },
{"id": "lavun", "name": "Lavun" },
{"id": "lere", "name": "Lere" },
{"id": "logo", "name": "Logo" },
{"id": "lokoja", "name": "Lokoja" },
{"id": "machina", "name": "Machina" },
{"id": "madagali", "name": "Madagali" },
{"id": "madobi", "name": "Madobi" },
{"id": "mafa", "name": "Mafa" },
{"id": "magama", "name": "Magama" },
{"id": "magumeri", "name": "Magumeri" },
{"id": "mai'adua", "name": "Mai'Adua" },
{"id": "maiduguri", "name": "Maiduguri" },
{"id": "maigatari", "name": "Maigatari" },
{"id": "maiha", "name": "Maiha" },
{"id": "maiyama", "name": "Maiyama" },
{"id": "makarfi", "name": "Makarfi" },
{"id": "malam madori", "name": "Malam Madori" },
{"id": "makoda", "name": "Makoda" },
{"id": "malumfashi", "name": "Malumfashi" },
{"id": "mangu", "name": "Mangu" },
{"id": "mani", "name": "Mani" },
{"id": "maradun", "name": "Maradun" },
{"id": "mariga", "name": "Mariga" },
{"id": "makurdi", "name": "Makurdi" },
{"id": "marte", "name": "Marte" },
{"id": "maru", "name": "Maru" },
{"id": "mashegu", "name": "Mashegu" },
{"id": "mashi", "name": "Mashi" },
{"id": "mayo belwa", "name": "Mayo Belwa" },
{"id": "mbaitoli", "name": "Mbaitoli" },
{"id": "mbo", "name": "Mbo" },
{"id": "michika", "name": "Michika" },
{"id": "miga", "name": "Miga" },
{"id": "mikang", "name": "Mikang" },
{"id": "minjibir", "name": "Minjibir" },
{"id": "misau", "name": "Misau" },
{"id": "moba", "name": "Moba" },
{"id": "mobbar", "name": "Mobbar" },
{"id": "mubi north", "name": "Mubi North" },
{"id": "mokwa", "name": "Mokwa" },
{"id": "monguno", "name": "Monguno" },
{"id": "mopa muro", "name": "Mopa Muro" },
{"id": "moro", "name": "Moro" },
{"id": "moya", "name": "Moya" },
{"id": "mkpat-enin", "name": "Mkpat-Enin" },
{"id": "municipal area council", "name": "Municipal Area Council" },
{"id": "musawa", "name": "Musawa" },
{"id": "mushin", "name": "Mushin" },
{"id": "nafada", "name": "Nafada" },
{"id": "nangere", "name": "Nangere" },
{"id": "nasarawa", "name": "Nasarawa" },
{"id": "nasarawa", "name": "Nasarawa" },
{"id": "nasarawa egon", "name": "Nasarawa Egon" },
{"id": "ndokwa east", "name": "Ndokwa East" },
{"id": "ndokwa west", "name": "Ndokwa West" },
{"id": "nembe", "name": "Nembe" },
{"id": "ngala", "name": "Ngala" },
{"id": "nganzai", "name": "Nganzai" },
{"id": "ngaski", "name": "Ngaski" },
{"id": "ngor okpala", "name": "Ngor Okpala" },
{"id": "nguru", "name": "Nguru" },
{"id": "ningi", "name": "Ningi" },
{"id": "njaba", "name": "Njaba" },
{"id": "njikoka", "name": "Njikoka" },
{"id": "nkanu east", "name": "Nkanu East" },
{"id": "nkanu west", "name": "Nkanu West" },
{"id": "nkwerre", "name": "Nkwerre" },
{"id": "nnewi north", "name": "Nnewi North" },
{"id": "nnewi south", "name": "Nnewi South" },
{"id": "nsit-atai", "name": "Nsit-Atai" },
{"id": "nsit-ibom", "name": "Nsit-Ibom" },
{"id": "nsit-ubium", "name": "Nsit-Ubium" },
{"id": "nsukka", "name": "Nsukka" },
{"id": "numan", "name": "Numan" },
{"id": "nwangele", "name": "Nwangele" },
{"id": "obafemi owode", "name": "Obafemi Owode" },
{"id": "kankia", "name": "Kankia" },
{"id": "obanliku", "name": "Obanliku" },
{"id": "obi", "name": "Obi" },
{"id": "obi", "name": "Obi" },
{"id": "obi ngwa", "name": "Obi Ngwa" },
{"id": "obio/akpor", "name": "Obio/Akpor" },
{"id": "obokun", "name": "Obokun" },
{"id": "obot akara", "name": "Obot Akara" },
{"id": "obowo", "name": "Obowo" },
{"id": "obubra", "name": "Obubra" },
{"id": "obudu", "name": "Obudu" },
{"id": "odeda", "name": "Odeda" },
{"id": "odigbo", "name": "Odigbo" },
{"id": "odogbolu", "name": "Odogbolu" },
{"id": "odo otin", "name": "Odo Otin" },
{"id": "odukpani", "name": "Odukpani" },
{"id": "offa", "name": "Offa" },
{"id": "ofu", "name": "Ofu" },
{"id": "ogba/egbema/ndoni", "name": "Ogba/Egbema/Ndoni" },
{"id": "ogbadibo", "name": "Ogbadibo" },
{"id": "ogbaru", "name": "Ogbaru" },
{"id": "ogbia", "name": "Ogbia" },
{"id": "ogbomosho north", "name": "Ogbomosho North" },
{"id": "ogbomosho south", "name": "Ogbomosho South" },
{"id": "mubi south", "name": "Mubi South" },
{"id": "ogu/bolo", "name": "Ogu/Bolo" },
{"id": "ogoja", "name": "Ogoja" },
{"id": "ogo oluwa", "name": "Ogo Oluwa" },
{"id": "ogun waterside", "name": "Ogun Waterside" },
{"id": "oguta", "name": "Oguta" },
{"id": "ohafia", "name": "Ohafia" },
{"id": "ohaji/egbema", "name": "Ohaji/Egbema" },
{"id": "ohaozara", "name": "Ohaozara" },
{"id": "ohaukwu", "name": "Ohaukwu" },
{"id": "ohimini", "name": "Ohimini" },
{"id": "orhionmwon", "name": "Orhionmwon" },
{"id": "ojo", "name": "Ojo" },
{"id": "oju", "name": "Oju" },
{"id": "oke ero", "name": "Oke Ero" },
{"id": "okene", "name": "Okene" },
{"id": "okitipupa", "name": "Okitipupa" },
{"id": "okigwe", "name": "Okigwe" },
{"id": "okobo", "name": "Okobo" },
{"id": "okpe", "name": "Okpe" },
{"id": "okrika", "name": "Okrika" },
{"id": "olamaboro", "name": "Olamaboro" },
{"id": "ola oluwa", "name": "Ola Oluwa" },
{"id": "olorunda", "name": "Olorunda" },
{"id": "oluyole", "name": "Oluyole" },
{"id": "olorunsogo", "name": "Olorunsogo" },
{"id": "omala", "name": "Omala" },
{"id": "omuma", "name": "Omuma" },
{"id": "ondo east", "name": "Ondo East" },
{"id": "ona ara", "name": "Ona Ara" },
{"id": "ondo west", "name": "Ondo West" },
{"id": "onicha", "name": "Onicha" },
{"id": "onitsha north", "name": "Onitsha North" },
{"id": "onitsha south", "name": "Onitsha South" },
{"id": "okpokwu", "name": "Okpokwu" },
{"id": "kazaure", "name": "Kazaure" },
{"id": "opobo/nkoro", "name": "Opobo/Nkoro" },
{"id": "oredo", "name": "Oredo" },
{"id": "orelope", "name": "Orelope" },
{"id": "oriade", "name": "Oriade" },
{"id": "ori ire", "name": "Ori Ire" },
{"id": "orlu", "name": "Orlu" },
{"id": "orolu", "name": "Orolu" },
{"id": "oron", "name": "Oron" },
{"id": "orsu", "name": "Orsu" },
{"id": "oru east", "name": "Oru East" },
{"id": "oruk anam", "name": "Oruk Anam" },
{"id": "orumba north", "name": "Orumba North" },
{"id": "orumba south", "name": "Orumba South" },
{"id": "oru west", "name": "Oru West" },
{"id": "ose", "name": "Ose" },
{"id": "oshimili north", "name": "Oshimili North" },
{"id": "oshimili south", "name": "Oshimili South" },
{"id": "oshodi-isolo", "name": "Oshodi-Isolo" },
{"id": "osisioma", "name": "Osisioma" },
{"id": "osogbo", "name": "Osogbo" },
{"id": "oturkpo", "name": "Oturkpo" },
{"id": "ovia north-east", "name": "Ovia North-East" },
{"id": "ovia south-west", "name": "Ovia South-West" },
{"id": "oji river", "name": "Oji River" },
{"id": "owan west", "name": "Owan West" },
{"id": "owerri municipal", "name": "Owerri Municipal" },
{"id": "owerri north", "name": "Owerri North" },
{"id": "owerri west", "name": "Owerri West" },
{"id": "owan east", "name": "Owan East" },
{"id": "owo", "name": "Owo" },
{"id": "oye", "name": "Oye" },
{"id": "oyi", "name": "Oyi" },
{"id": "oyigbo", "name": "Oyigbo" },
{"id": "oyo", "name": "Oyo" },
{"id": "oyo east", "name": "Oyo East" },
{"id": "oyun", "name": "Oyun" },
{"id": "paikoro", "name": "Paikoro" },
{"id": "pankshin", "name": "Pankshin" },
{"id": "patani", "name": "Patani" },
{"id": "pategi", "name": "Pategi" },
{"id": "port harcourt", "name": "Port Harcourt" },
{"id": "potiskum", "name": "Potiskum" },
{"id": "qua'an pan", "name": "Qua'an Pan" },
{"id": "rabah", "name": "Rabah" },
{"id": "rafi", "name": "Rafi" },
{"id": "rano", "name": "Rano" },
{"id": "remo north", "name": "Remo North" },
{"id": "rijau", "name": "Rijau" },
{"id": "rimi", "name": "Rimi" },
{"id": "rimin gado", "name": "Rimin Gado" },
{"id": "ringim", "name": "Ringim" },
{"id": "riyom", "name": "Riyom" },
{"id": "rogo", "name": "Rogo" },
{"id": "roni", "name": "Roni" },
{"id": "sabon birni", "name": "Sabon Birni" },
{"id": "sabon gari", "name": "Sabon Gari" },
{"id": "sabuwa", "name": "Sabuwa" },
{"id": "safana", "name": "Safana" },
{"id": "sagbama", "name": "Sagbama" },
{"id": "sakaba", "name": "Sakaba" },
{"id": "saki east", "name": "Saki East" },
{"id": "saki west", "name": "Saki West" },
{"id": "sandamu", "name": "Sandamu" },
{"id": "sanga", "name": "Sanga" },
{"id": "sapele", "name": "Sapele" },
{"id": "sardauna", "name": "Sardauna" },
{"id": "shagamu", "name": "Shagamu" },
{"id": "shagari", "name": "Shagari" },
{"id": "shanga", "name": "Shanga" },
{"id": "shani", "name": "Shani" },
{"id": "shelleng", "name": "Shelleng" },
{"id": "shendam", "name": "Shendam" },
{"id": "shinkafi", "name": "Shinkafi" },
{"id": "shira", "name": "Shira" },
{"id": "shiroro", "name": "Shiroro" },
{"id": "shongom", "name": "Shongom" },
{"id": "shomolu", "name": "Shomolu" },
{"id": "soba", "name": "Soba" },
{"id": "silame", "name": "Silame" },
{"id": "matazu", "name": "Matazu" },
{"id": "sokoto north", "name": "Sokoto North" },
{"id": "southern ijaw", "name": "Southern Ijaw" },
{"id": "sokoto south", "name": "Sokoto South" },
{"id": "song", "name": "Song" },
{"id": "suleja", "name": "Suleja" },
{"id": "sumaila", "name": "Sumaila" },
{"id": "sule tankarkar", "name": "Sule Tankarkar" },
{"id": "onna", "name": "Onna" },
{"id": "suru", "name": "Suru" },
{"id": "surulere", "name": "Surulere" },
{"id": "surulere", "name": "Surulere" },
{"id": "tafa", "name": "Tafa" },
{"id": "tafawa balewa", "name": "Tafawa Balewa" },
{"id": "tai", "name": "Tai" },
{"id": "takai", "name": "Takai" },
{"id": "takum", "name": "Takum" },
{"id": "talata mafara", "name": "Talata Mafara" },
{"id": "tambuwal", "name": "Tambuwal" },
{"id": "tangaza", "name": "Tangaza" },
{"id": "tarauni", "name": "Tarauni" },
{"id": "tarka", "name": "Tarka" },
{"id": "taura", "name": "Taura" },
{"id": "tofa", "name": "Tofa" },
{"id": "toungo", "name": "Toungo" },
{"id": "tarmuwa", "name": "Tarmuwa" },
{"id": "chafe", "name": "Chafe" },
{"id": "toro", "name": "Toro" },
{"id": "toto", "name": "Toto" },
{"id": "tsanyawa", "name": "Tsanyawa" },
{"id": "tudun wada", "name": "Tudun Wada" },
{"id": "tureta", "name": "Tureta" },
{"id": "udenu", "name": "Udenu" },
{"id": "udi", "name": "Udi" },
{"id": "udu", "name": "Udu" },
{"id": "udung-uko", "name": "Udung-Uko" },
{"id": "ughelli north", "name": "Ughelli North" },
{"id": "ughelli south", "name": "Ughelli South" },
{"id": "ugwunagbo", "name": "Ugwunagbo" },
{"id": "uhunmwonde", "name": "Uhunmwonde" },
{"id": "ukanafun", "name": "Ukanafun" },
{"id": "ukum", "name": "Ukum" },
{"id": "ukwa east", "name": "Ukwa East" },
{"id": "ukwa west", "name": "Ukwa West" },
{"id": "ukwuani", "name": "Ukwuani" },
{"id": "umuahia north", "name": "Umuahia North" },
{"id": "umuahia south", "name": "Umuahia South" },
{"id": "umu nneochi", "name": "Umu Nneochi" },
{"id": "ungogo", "name": "Ungogo" },
{"id": "unuimo", "name": "Unuimo" },
{"id": "uruan", "name": "Uruan" },
{"id": "urue-offong/oruko", "name": "Urue-Offong/Oruko" },
{"id": "ushongo", "name": "Ushongo" },
{"id": "ussa", "name": "Ussa" },
{"id": "uvwie", "name": "Uvwie" },
{"id": "uyo", "name": "Uyo" },
{"id": "uzo-uwani", "name": "Uzo-Uwani" },
{"id": "vandeikya", "name": "Vandeikya" },
{"id": "wamako", "name": "Wamako" },
{"id": "wamba", "name": "Wamba" },
{"id": "warawa", "name": "Warawa" },
{"id": "warri south", "name": "Warri South" },
{"id": "warji", "name": "Warji" },
{"id": "warri south west", "name": "Warri South West" },
{"id": "wasagu/danko", "name": "Wasagu/Danko" },
{"id": "wase", "name": "Wase" },
{"id": "wudil", "name": "Wudil" },
{"id": "wukari", "name": "Wukari" },
{"id": "wurno", "name": "Wurno" },
{"id": "wushishi", "name": "Wushishi" },
{"id": "yabo", "name": "Yabo" },
{"id": "yagba east", "name": "Yagba East" },
{"id": "yagba west", "name": "Yagba West" },
{"id": "yakuur", "name": "Yakuur" },
{"id": "obi", "name": "Obi" },
{"id": "obi", "name": "Obi" },
{"id": "obi ngwa", "name": "Obi Ngwa" },
{"id": "obio/akpor", "name": "Obio/Akpor" },
{"id": "obokun", "name": "Obokun" },
{"id": "obot akara", "name": "Obot Akara" },
{"id": "obowo", "name": "Obowo" },
{"id": "obubra", "name": "Obubra" },
{"id": "yamaltu/deba", "name": "Yamaltu/Deba" },
{"id": "yala", "name": "Yala" },
{"id": "yankwashi", "name": "Yankwashi" },
{"id": "yauri", "name": "Yauri" },
{"id": "yenagoa", "name": "Yenagoa" },
{"id": "yola north", "name": "Yola North" },
{"id": "yola south", "name": "Yola South" },
{"id": "yorro", "name": "Yorro" },
{"id": "yusufari", "name": "Yusufari" },
{"id": "yunusari", "name": "Yunusari" },
{"id": "zaki", "name": "Zaki" },
{"id": "zango", "name": "Zango" },
{"id": "zaria", "name": "Zaria" },
{"id": "zing", "name": "Zing" },
{"id": "zurmi", "name": "Zurmi" },
{"id": "zuru", "name": "Zuru" },
{"id": "shanono", "name": "Shanono" },
{"id": "okehi", "name": "Okehi" },
{"id": "ogori/magongo", "name": "Ogori/Magongo" },
{"id": "warri north", "name": "Warri North" },
{"id": "zangon kataf", "name": "Zangon Kataf" },
]